apiVersion: v1
kind: Secret
metadata:
  name: banking-app-secrets
  namespace: banking-app
  labels:
    app: banking-app
    environment: development
    security: high
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  # Example: echo -n "your-password" | base64
  db-password: eW91ci1zZWN1cmUtcGFzc3dvcmQ=  # Replace with actual base64 encoded password
  jwt-secret: eW91ci1qd3Qtc2VjcmV0LWtleQ==  # Replace with actual base64 encoded JWT secret
  encryption-key: eW91ci1lbmNyeXB0aW9uLWtleQ==  # Replace with actual base64 encoded encryption key
---
apiVersion: v1
kind: Secret
metadata:
  name: banking-app-tls
  namespace: banking-app
  labels:
    app: banking-app
    environment: development
    security: high
type: kubernetes.io/tls
data:
  # Base64 encoded TLS certificate and key
  # Example: cat tls.crt | base64
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCg==  # Replace with actual certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCg==  # Replace with actual private key 